### ISSUE TITLE
Running the script as root won't be allowed

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/containers-recipes#2]
Won't be running this script as root

https://github.com/ComputeCanada/containers-recipes/blob/708cf64681165d741922a3e9b9658b2a80fa5635/build_container_image.sh#L199

@BioBP

**Comment by mboisson** [comment]
Here are scenarios, from the most preferred one to the least preferred one: 

1. We forgo `docker` completely. Replace it with a tool that runs in user-space
2. We figure out how to run `docker` as non-root, with a special user with special permissions
3. We use `sudo` only for the required `docker` commands within the script

but we do *not* run the script as root.

**Comment by preney** [comment]
Issue note for others here: `spython` is this: https://github.com/singularityhub/singularity-cli.git (or https://singularityhub.github.io/singularity-cli/install ).

**Comment by preney** [comment]
Before posting about Option 1... For those with Docker access (on their own machine or otherwise), one can create an Apptainer image from a `Dockerfile` using Docker as is detailed below (summarized from internal SHARCNET documentation I wrote on this issue).

### Steps To Go From a Dockerfile To an Apptainer Image
NOTE: Using Docker may fail if you are not in the docker group. Ask to be added to the docker group on that system if such is needed.

If one only has a Dockerfile and wishes to create an Apptainer image, do the following:

    docker build -f Dockerfile -t your-tag-name
    docker save your-tag-name -o your-tarball-name.tar
    docker image rm your-tag-name
    apptainer build --fakeroot your-sif-name.sif docker-archive://your-tarball-name.tar
    rm -f your-tarball-name.tar

Additionally, if the Dockerfile pulled in more layers, you will have to manually delete such by running:

    docker images

and then run docker image rm ID (where ID is the image ID previously output) in order to free up the disk space from such.

**Comment by preney** [comment]
While I understand why building images without root is very desirable, in my experience, it is often not realistic. Instead of me listing some points, consider `podman`'s not-at-all-short **Shortcomings of Rootless Podman** documentation here https://github.com/containers/podman/blob/main/rootless.md . This (plus or minus a couple of items) essentially applies to *any* container technology. Personally, my view is that virtually all container images should be built with root on some suitable system (e.g., a home/lab computer, within a virtual machine, a cloud virtual machine node that is started up and used for that purpose and then destroyed, etc.) and then copied to the clusters.

An item that is often overlooked is that building container images on NFS or otherwise networked file systems can often fail. Building images should be done on local disk space. This is also for practical/efficiency reasons: larger images will need to copy many gigabytes of data by the time the image build is done as the image building process involves reading, writing, etc. files many times over.

**Comment by mboisson** [comment]
This was resolved by using `podman` instead of `docker`
